//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsignacion
    {
        public int IDAsignacion { get; set; }
        public string EstadoAsignacion { get; set; }
        public int FKEmpleado { get; set; }
        public int FKProblemas { get; set; }
    
        public virtual tblEmpleado tblEmpleado { get; set; }
    }
}
