//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProblema
    {
        public int IDProblema { get; set; }
        public string TituloProblema { get; set; }
        public string DescripcionProblema { get; set; }
        public System.DateTime FechaProblema { get; set; }
        public int FKProyecto { get; set; }
        public int FKCliente { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
    }
}
