//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProyectos
    {
        public int IDProyecto { get; set; }
        public string NombreProyecto { get; set; }
        public string DescripcionProyecto { get; set; }
        public string PrioridadProyecto { get; set; }
        public System.DateTime FechaProyecto { get; set; }
        public string EstadoProyecto { get; set; }
        public int FKCliente { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
    }
}
