//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Manager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTarjeta
    {
        public int IDTarjeta { get; set; }
        public string NumeroTarjeta { get; set; }
        public string CVVTarjeta { get; set; }
        public string FechaTarjeta { get; set; }
        public int FKCliente { get; set; }
    
        public virtual tblEmpleado tblEmpleado { get; set; }
    }
}
